name: Publish Docker image
on:
  push:
    branches:
      - main
jobs:
  build_and_push:
    name: Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            girona/telegram-bot-picateclas:latest
            girona/telegram-bot-picateclas:${{ github.sha }}
  deploy_to_server:
    needs: build_and_push
    name: Deploy to docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Docker
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: ${{ secrets.DOCKER_HOST }}
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          copy_stack_file: true
          deploy_path: /home/picateclas/telegram-bot-picateclas
          stack_file_name: docker-compose.yaml
          keep_files: 3
          args: telegram-bot-picateclas
